services:
  master:
    build:
      context: .
      dockerfile: go-master/Dockerfile.master
    ports:
      - "${PORT}:${PORT}"
    volumes:
      # Mount the whole root so we can access any file relative to it
      - .:/app
    environment: # to pass to go binary
      - FILE=${FILE}
      - PORT=${PORT}
    # We pass the FILE variable directly to the binary
    command: ./master_bin /app/${FILE}

  worker-swarm:
    build:
      context: .
      dockerfile: python-worker/Dockerfile.worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MASTER_ADDR=${MASTER_ADDR:-master}:${PORT}
      - CORES=${CORES:-1}
