# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'solver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csolver.proto\"$\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x83\x01\n\x0c\x43ountRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12\x10\n\x08num_vars\x18\x02 \x01(\x05\x12\x13\n\x0bnum_clauses\x18\x03 \x01(\x05\x12\x14\n\x0c\x66ormula_body\x18\x04 \x01(\t\x12\x10\n\x08literals\x18\x05 \x03(\x05\x12\x13\n\x0btimeout_sec\x18\x06 \x01(\x05\"k\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x02 \x01(\x01\x12\x11\n\ttimed_out\x18\x03 \x01(\x08\x12\x0f\n\x07task_id\x18\x04 \x01(\x03\x12\x11\n\tworker_id\x18\x05 \x01(\t2c\n\rSolverService\x12*\n\x07GetTask\x12\x10.RegisterRequest\x1a\r.CountRequest\x12&\n\x0cSubmitResult\x12\x0e.CountResponse\x1a\x06.EmptyB\x1bZ\x19HydraSAT/src/master/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031HydraSAT/src/master/proto'
  _globals['_REGISTERREQUEST']._serialized_start=16
  _globals['_REGISTERREQUEST']._serialized_end=52
  _globals['_EMPTY']._serialized_start=54
  _globals['_EMPTY']._serialized_end=61
  _globals['_COUNTREQUEST']._serialized_start=64
  _globals['_COUNTREQUEST']._serialized_end=195
  _globals['_COUNTRESPONSE']._serialized_start=197
  _globals['_COUNTRESPONSE']._serialized_end=304
  _globals['_SOLVERSERVICE']._serialized_start=306
  _globals['_SOLVERSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
