# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import solver_pb2 as solver__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in solver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolverServiceStub(object):
    """=== WORKER <-> MASTER RPCs ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/SolverService/GetTask',
                request_serializer=solver__pb2.WorkerIdentity.SerializeToString,
                response_deserializer=solver__pb2.TaskPayload.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/SolverService/SubmitResult',
                request_serializer=solver__pb2.TaskResult.SerializeToString,
                response_deserializer=solver__pb2.Empty.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/SolverService/ReportStatus',
                request_serializer=solver__pb2.WorkerStatus.SerializeToString,
                response_deserializer=solver__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMasterStats = channel.unary_unary(
                '/SolverService/GetMasterStats',
                request_serializer=solver__pb2.Empty.SerializeToString,
                response_deserializer=solver__pb2.MasterStatsResponse.FromString,
                _registered_method=True)
        self.SubscribeTimeoutUpdates = channel.unary_stream(
                '/SolverService/SubscribeTimeoutUpdates',
                request_serializer=solver__pb2.WorkerIdentity.SerializeToString,
                response_deserializer=solver__pb2.TimeoutUpdate.FromString,
                _registered_method=True)


class SolverServiceServicer(object):
    """=== WORKER <-> MASTER RPCs ===
    """

    def GetTask(self, request, context):
        """1. Worker asks for a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """2. Worker submits the final count/timeout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """3. Worker streams its live CPU/RAM while ganak is running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMasterStats(self, request, context):
        """=== TUI <-> MASTER RPCs ===

        4. TUI asks for the global state to draw the UI
        We use Empty instead of a useless StatsRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTimeoutUpdates(self, request, context):
        """Worker subscribes once; master pushes TimeoutUpdate whenever the
        dynamic timeout changes meaningfully.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=solver__pb2.WorkerIdentity.FromString,
                    response_serializer=solver__pb2.TaskPayload.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=solver__pb2.TaskResult.FromString,
                    response_serializer=solver__pb2.Empty.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=solver__pb2.WorkerStatus.FromString,
                    response_serializer=solver__pb2.Empty.SerializeToString,
            ),
            'GetMasterStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMasterStats,
                    request_deserializer=solver__pb2.Empty.FromString,
                    response_serializer=solver__pb2.MasterStatsResponse.SerializeToString,
            ),
            'SubscribeTimeoutUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTimeoutUpdates,
                    request_deserializer=solver__pb2.WorkerIdentity.FromString,
                    response_serializer=solver__pb2.TimeoutUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SolverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SolverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolverService(object):
    """=== WORKER <-> MASTER RPCs ===
    """

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SolverService/GetTask',
            solver__pb2.WorkerIdentity.SerializeToString,
            solver__pb2.TaskPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SolverService/SubmitResult',
            solver__pb2.TaskResult.SerializeToString,
            solver__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SolverService/ReportStatus',
            solver__pb2.WorkerStatus.SerializeToString,
            solver__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMasterStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SolverService/GetMasterStats',
            solver__pb2.Empty.SerializeToString,
            solver__pb2.MasterStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTimeoutUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SolverService/SubscribeTimeoutUpdates',
            solver__pb2.WorkerIdentity.SerializeToString,
            solver__pb2.TimeoutUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
