// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: solver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolverService_GetTask_FullMethodName        = "/SolverService/GetTask"
	SolverService_SubmitResult_FullMethodName   = "/SolverService/SubmitResult"
	SolverService_ReportStatus_FullMethodName   = "/SolverService/ReportStatus"
	SolverService_GetMasterStats_FullMethodName = "/SolverService/GetMasterStats"
)

// SolverServiceClient is the client API for SolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverServiceClient interface {
	// 1. Worker asks for a task
	GetTask(ctx context.Context, in *WorkerIdentity, opts ...grpc.CallOption) (*TaskPayload, error)
	// 2. Worker submits the final count/timeout
	SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error)
	// 3. Worker streams its live CPU/RAM while ganak is running
	ReportStatus(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*Empty, error)
	// 4. TUI asks for the global state to draw the UI
	// We use Empty instead of a useless StatsRequest
	GetMasterStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MasterStatsResponse, error)
}

type solverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverServiceClient(cc grpc.ClientConnInterface) SolverServiceClient {
	return &solverServiceClient{cc}
}

func (c *solverServiceClient) GetTask(ctx context.Context, in *WorkerIdentity, opts ...grpc.CallOption) (*TaskPayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPayload)
	err := c.cc.Invoke(ctx, SolverService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solverServiceClient) SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SolverService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solverServiceClient) ReportStatus(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SolverService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solverServiceClient) GetMasterStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MasterStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterStatsResponse)
	err := c.cc.Invoke(ctx, SolverService_GetMasterStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverServiceServer is the server API for SolverService service.
// All implementations must embed UnimplementedSolverServiceServer
// for forward compatibility.
type SolverServiceServer interface {
	// 1. Worker asks for a task
	GetTask(context.Context, *WorkerIdentity) (*TaskPayload, error)
	// 2. Worker submits the final count/timeout
	SubmitResult(context.Context, *TaskResult) (*Empty, error)
	// 3. Worker streams its live CPU/RAM while ganak is running
	ReportStatus(context.Context, *WorkerStatus) (*Empty, error)
	// 4. TUI asks for the global state to draw the UI
	// We use Empty instead of a useless StatsRequest
	GetMasterStats(context.Context, *Empty) (*MasterStatsResponse, error)
	mustEmbedUnimplementedSolverServiceServer()
}

// UnimplementedSolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolverServiceServer struct{}

func (UnimplementedSolverServiceServer) GetTask(context.Context, *WorkerIdentity) (*TaskPayload, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedSolverServiceServer) SubmitResult(context.Context, *TaskResult) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedSolverServiceServer) ReportStatus(context.Context, *WorkerStatus) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedSolverServiceServer) GetMasterStats(context.Context, *Empty) (*MasterStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterStats not implemented")
}
func (UnimplementedSolverServiceServer) mustEmbedUnimplementedSolverServiceServer() {}
func (UnimplementedSolverServiceServer) testEmbeddedByValue()                       {}

// UnsafeSolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverServiceServer will
// result in compilation errors.
type UnsafeSolverServiceServer interface {
	mustEmbedUnimplementedSolverServiceServer()
}

func RegisterSolverServiceServer(s grpc.ServiceRegistrar, srv SolverServiceServer) {
	// If the following call panics, it indicates UnimplementedSolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolverService_ServiceDesc, srv)
}

func _SolverService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).GetTask(ctx, req.(*WorkerIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolverService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).SubmitResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolverService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).ReportStatus(ctx, req.(*WorkerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolverService_GetMasterStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).GetMasterStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_GetMasterStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).GetMasterStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SolverService_ServiceDesc is the grpc.ServiceDesc for SolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SolverService",
	HandlerType: (*SolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _SolverService_GetTask_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _SolverService_SubmitResult_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _SolverService_ReportStatus_Handler,
		},
		{
			MethodName: "GetMasterStats",
			Handler:    _SolverService_GetMasterStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solver.proto",
}
