// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: solver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // ID of the worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_solver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_solver_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_solver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_solver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_solver_proto_rawDescGZIP(), []int{1}
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`               // unique ID for the counting task
	NumVars       int32                  `protobuf:"varint,2,opt,name=num_vars,json=numVars,proto3" json:"num_vars,omitempty"`            // number of variables in the CNF
	NumClauses    int32                  `protobuf:"varint,3,opt,name=num_clauses,json=numClauses,proto3" json:"num_clauses,omitempty"`   // number of clauses in the CNF
	FormulaBody   string                 `protobuf:"bytes,4,opt,name=formula_body,json=formulaBody,proto3" json:"formula_body,omitempty"` // raw DIMACS body of the CNF (without the header)
	Literals      []int32                `protobuf:"varint,5,rep,packed,name=literals,proto3" json:"literals,omitempty"`                  // the cube
	TimeoutSec    int32                  `protobuf:"varint,6,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`   // timeout in seconds for the solver to find a solution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_solver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_solver_proto_rawDescGZIP(), []int{2}
}

func (x *CountRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CountRequest) GetNumVars() int32 {
	if x != nil {
		return x.NumVars
	}
	return 0
}

func (x *CountRequest) GetNumClauses() int32 {
	if x != nil {
		return x.NumClauses
	}
	return 0
}

func (x *CountRequest) GetFormulaBody() string {
	if x != nil {
		return x.FormulaBody
	}
	return ""
}

func (x *CountRequest) GetLiterals() []int32 {
	if x != nil {
		return x.Literals
	}
	return nil
}

func (x *CountRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         string                 `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`                                  // the number of solutions as a string to handle large numbers
	DurationSec   float64                `protobuf:"fixed64,2,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"` // time taken to solve in seconds
	TimedOut      bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`           // indicates if the solver timed out
	TaskId        int64                  `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                 // the ID of the task (for tracking purposes)
	WorkerId      string                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`            // the ID of the worker that processed this task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_solver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_solver_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

func (x *CountResponse) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *CountResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *CountResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CountResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_solver_proto protoreflect.FileDescriptor

const file_solver_proto_rawDesc = "" +
	"\n" +
	"\fsolver.proto\".\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\a\n" +
	"\x05Empty\"\xc3\x01\n" +
	"\fCountRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x19\n" +
	"\bnum_vars\x18\x02 \x01(\x05R\anumVars\x12\x1f\n" +
	"\vnum_clauses\x18\x03 \x01(\x05R\n" +
	"numClauses\x12!\n" +
	"\fformula_body\x18\x04 \x01(\tR\vformulaBody\x12\x1a\n" +
	"\bliterals\x18\x05 \x03(\x05R\bliterals\x12\x1f\n" +
	"\vtimeout_sec\x18\x06 \x01(\x05R\n" +
	"timeoutSec\"\x9b\x01\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\tR\x05count\x12!\n" +
	"\fduration_sec\x18\x02 \x01(\x01R\vdurationSec\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId2c\n" +
	"\rSolverService\x12*\n" +
	"\aGetTask\x12\x10.RegisterRequest\x1a\r.CountRequest\x12&\n" +
	"\fSubmitResult\x12\x0e.CountResponse\x1a\x06.EmptyB\x1bZ\x19HydraSAT/src/master/protob\x06proto3"

var (
	file_solver_proto_rawDescOnce sync.Once
	file_solver_proto_rawDescData []byte
)

func file_solver_proto_rawDescGZIP() []byte {
	file_solver_proto_rawDescOnce.Do(func() {
		file_solver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_solver_proto_rawDesc), len(file_solver_proto_rawDesc)))
	})
	return file_solver_proto_rawDescData
}

var file_solver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_solver_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: RegisterRequest
	(*Empty)(nil),           // 1: Empty
	(*CountRequest)(nil),    // 2: CountRequest
	(*CountResponse)(nil),   // 3: CountResponse
}
var file_solver_proto_depIdxs = []int32{
	0, // 0: SolverService.GetTask:input_type -> RegisterRequest
	3, // 1: SolverService.SubmitResult:input_type -> CountResponse
	2, // 2: SolverService.GetTask:output_type -> CountRequest
	1, // 3: SolverService.SubmitResult:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_solver_proto_init() }
func file_solver_proto_init() {
	if File_solver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_solver_proto_rawDesc), len(file_solver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_solver_proto_goTypes,
		DependencyIndexes: file_solver_proto_depIdxs,
		MessageInfos:      file_solver_proto_msgTypes,
	}.Build()
	File_solver_proto = out.File
	file_solver_proto_goTypes = nil
	file_solver_proto_depIdxs = nil
}
