FROM golang:1.26.1-alpine AS builder
WORKDIR /build

# Copy the go.mod and go.sum from the subfolder
COPY go-master/go.mod go-master/go.sum ./
RUN go mod download

# Copy the rest of the Master source and the shared Protos
COPY go-master/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o master_bin ./master
RUN chmod +x master_bin

FROM alpine:latest
WORKDIR /app
COPY --from=builder /build/master_bin /usr/local/bin/master_bin

# Expose the gRPC port
EXPOSE 50051

CMD ["master_bin"]
